Remove severity from compatibility warning
Turns out it's hard to give this a very strict meaning. So far it's been
something like:

  Error: This is a guaranteed problem
  Warning: This might not be a problem if the user does a very specific
           thing

Warning arguably sounds to weak though, likely the user does need to
take immediate action when seeing a warning.

Rather than expending effort playing a classification game, let's just
tell the user what's up and let them decide what they need to do about
it.